use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :flyiin_assignment, FlyiinAssignmentWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :flyiin_assignment, FlyiinAssignmentWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/flyiin_assignment_web/{live,views}/.*(ex)$",
      ~r"lib/flyiin_assignment_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :flyiin_assignment, FlyiinAssignment.Airline.AirFranceKLM,
  travel_agency: %{name: "test", city: "PARMM211L", iata_number: "12345675", id: "id"},
  headers: [
    {"SOAPAction",
     "\"http://www.af-klm.com/services/passenger/ProvideAirShopping/provideAirShopping\""},
    {"Content-Type", "text/xml"},
    {"api_key", System.fetch_env!("AIR_FRANCE_KLM_API_KEY")}
  ],
  url: "https://ndc-rct.airfranceklm.com/passenger/distribmgmt/001448v01/EXT"

config :flyiin_assignment, FlyiinAssignment.Airline.BritishAirways,
  travel_agency: %{name: "test agent", city: "", iata_number: "00002004", id: "test agent"},
  headers: [
    {"SOAPAction", "AirShoppingV01"},
    {"Content-Type", "application/xml"},
    {"Client-Key", System.fetch_env!("BRITISH_AIRWAYS_API_KEY")}
  ],
  url: "https://test.api.ba.com/selling-distribution/AirShopping/V2"
